services:
  db:
    image: postgres:latest
    restart: always
    container_name: workout-tracker-db
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database-workout-tracker
    ports:
      - "5432:5432"
    volumes:
      - workout-data:/var/lib/postgresql
      - ./db/create-initial-schema.sql:/docker-entrypoint-initdb.d/initial-schema-setup.sql

volumes:
  workout-data:

