services:
  dbmongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: workoutdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  workout-app:
    build: .
    container_name: workout-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - dbmongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@dbmongo:27017/workoutdb?authSource=admin
      SPRING_DATA_MONGODB_DATABASE: workoutdb

volumes:
  mongo-data: